apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aurison-backend.fullname" . }}-ws
  labels:
    {{- include "aurison-backend.labels" . | nindent 4 }}
    app: aurison-backend-ws
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: aurison-backend-ws
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: aurison-backend-ws
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aurison-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - -c
            - |
              echo "Waiting for main backend to be ready..."
              until nc -z {{ include "aurison-backend.fullname" . }} {{ .Values.service.port }}; do
                echo "Backend not ready, waiting 5 seconds..."
                sleep 5
              done
              echo "Backend is ready!"
      containers:
        - name: {{ .Chart.Name }}-ws
          command: 
            {{- toYaml .Values.aurisonBackendWs.command | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: websocket
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.aurisonBackendWs.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
