{{- if .Values.aurisonBackendPacs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aurison-backend.fullname" . }}-pacs
  labels:
    {{- include "aurison-backend.labels" . | nindent 4 }}
    app: aurison-backend-pacs
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.aurisonBackendPacs.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: aurison-backend-pacs
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: aurison-backend-pacs
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aurison-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pacs
          command: 
            {{- toYaml .Values.aurisonBackendPacs.command | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pacs-ws
              containerPort: {{ .Values.aurisonBackendPacs.port | default 8001 }}
              protocol: TCP
          {{- if .Values.mtls.enabled }}
          volumeMounts:
            - name: ca-cert-volume
              mountPath: /app/certs/
              readOnly: true
          env:
            - name: MTLS_CA_CERT_PATH
              value: "/app/certs/ca-certificate.pem"
            - name: MTLS_CA_KEY_PATH
              value: "/app/certs/ca-private-key.pem"
            - name: MTLS_ENABLED
              value: "true"
          {{- end }}
          resources:
            {{- toYaml .Values.aurisonBackendPacs.resources | nindent 12 }}
      {{- if .Values.mtls.enabled }}
      volumes:
        - name: ca-cert-volume
          secret:
            secretName: {{ if .Values.mtls.existingSecret }}aurison-backend-ca-secret-cert{{ else }}{{ include "aurison-backend.fullname" . }}-ca-secret-cert{{ end }}
            items:
              - key: ca-certificate.pem
                path: ca-certificate.pem
              - key: ca-private-key.pem
                path: ca-private-key.pem
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}