apiVersion: v1
kind: Service
metadata:
  name: aurison-backend-ws
  labels:
    {{- include "aurison-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    app: aurison-backend-ws